name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 18.x
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Run Unit Tests and generate coverage report
        working-directory: ./
        run: npm run test
